spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainingdb
    username: root
    password: Rohit@2000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true